### PR TITLE
remove asserts from production code

### LINKED ISSUE #22: CURL is using `assert` in production code
The library uses `assert` in the production code a couple of times, e.g.
```java
public static String curl_easy_getinfo_String(@NativeType ("CURL *") long curl, @NativeType ("CURLINFO") int opt) {
    assert (opt & CURLINFO_TYPEMASK) == CURLINFO_STRING;
```

By default, assertions are disabled at runtime (see [here](https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html)). They have to be explicitly enabled via `java -enableassertions your_program.jar` to make them work.

So if someone uses the wrong `opt` outside of tests, like this:
```
CURL.curl_easy_getinfo_String(curlHandle, CURLINFO_HTTP_VERSION);
```
Then no exception will be thrown but instead he gets a `SIGSEGV`. This is especially bad in a multi-threaded environment where this can lead to memory leaks and obscure bugs.

You can test Java's default behavior with this:
```java
public class AssertTest {

    public static void main(String[] args) {
        assert "not null".equals(null);
        if (!"not null".equals(null)) {
            throw new AssertionError("Assertion failed");
        }
    }

    @Test
    void runAsTest() {
        assert "not null".equals(null);
    }
}
```
If you run `runAsTest()` then the `assert` throws an exception. If you run `main()` then the `assert` is ignored.

The `assert`'s should therefore be replaced with regular exceptions.

### PR DESCRIPTION
**Pull request by ss3rg3**
Fixes #22

For testing I extended CURLTests.testDownload() instead of creating a new method in order to not clog up the class.

### CODE REVIEW

File: src/main/java/net/covers1624/curl4j/core/Callback.java [hunk 1]
```diff
@@ -158,7 +158,9 @@ protected static long ffi_prep_cif(long rtype, long... atypes) {
 
     // Invoked by JNI in native land, simply forwards the callback through.
     private void ffi_callback(long ret, long args) throws Throwable {
-        assert delegate != null;
+        if (delegate == null) {
```
Comment (covers1624) [inline src/main/java/net/covers1624/curl4j/core/Callback.java:161]: This can just be removed altogether. It's guaranteed to be non-null.

**Review by covers1624 — CHANGES_REQUESTED** [review]
Looks good. Just a minor change.

**Comment by covers1624** [comment]
Thanks again!

I'll create another release shortly, but this will be up as a SNAPSHOT build once CI finishes.

File: src/main/java/net/covers1624/curl4j/core/Callback.java (hunk 1 above)
Comment (covers1624) [reply src/main/java/net/covers1624/curl4j/core/Callback.java]: I should also clarify, those constructors may seem dead, but they are marked as `protected` specifically to allow sub-classing and overriding of the `read` or `write`, etc methods.

I found this quite useful in other projects when my callback needed a bunch of state and I wanted to isolate it.
